<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Symfony\Component\Console\Attribute\AsCommand;

#[AsCommand(
    name: 'columns:export',
    description: 'Export model columns() definitions to TypeScript'
)]
class ExportColumns extends Command
{
    protected $signature = 'columns:export';

    protected $description = 'Export model columns() definitions to TypeScript';

    public function handle()
    {
        $models = $this->discoverModels();

        foreach ($models as $class) {
            if (!method_exists($class, 'columns')) continue;

            $columns = $class::columns();
            if (empty($columns)) continue;

            $name = class_basename($class);
            $this->info("Exporting {$name}...");

            $ts = $this->generateTypeScript($name, $columns);

            $outputPath = resource_path("js/types/generated/{$name}Fields.ts");
            File::ensureDirectoryExists(dirname($outputPath));
            File::put($outputPath, $ts);

            $this->info("  → {$outputPath}");
        }

        $this->info('Done.');

        return Command::SUCCESS;
    }

    private function discoverModels(): array
    {
        $dir = app_path('Models');
        $files = File::allFiles($dir);

        $models = [];
        foreach ($files as $file) {
            if ($file->getExtension() !== 'php') continue;

            $relative = str_replace(['/', '\\'], '\\', $file->getRelativePathname());
            $class = 'App\\Models\\'.str_replace('.php', '', $relative);

            if (class_exists($class)) {
                $models[] = $class;
            }
        }

        return $models;
    }

    private function generateTypeScript(string $name, array $columns): string
    {
        $fields = [];
        foreach ($columns as $key => $meta) {
            $fields[] = $this->formatField($key, $meta);
        }

        $fieldEntries = implode(",\n  ", $fields);

        $lines = [];
        $lines[] = '// Auto-generated by `php artisan columns:export`. DO NOT EDIT.';
        $lines[] = '';
        $lines[] = "export const ".strtoupper($name)."_FIELDS = {";
        $lines[] = "  {$fieldEntries}";
        $lines[] = '} as const;';
        $lines[] = '';
        $lines[] = "export type {$name}FieldName = keyof typeof ".strtoupper($name)."_FIELDS;";
        $lines[] = "export type {$name}Field = (typeof ".strtoupper($name)."_FIELDS)[{$name}FieldName];";

        return implode("\n", $lines)."\n";
    }

    private function formatField(string $key, array $meta): string
    {
        $props = ['name: '.json_encode($key)];

        foreach (['label', 'type', 'filter', 'sort', 'search', 'rules'] as $attr) {
            if (isset($meta[$attr])) {
                $val = $meta[$attr];
                if (is_bool($val)) {
                    $props[] = "{$attr}: ".($val ? 'true' : 'false').' as const';
                } else {
                    $props[] = "{$attr}: ".json_encode($val).' as const';
                }
            }
        }

        foreach (['filter_class', 'filter_column', 'sort_column'] as $attr) {
            if (isset($meta[$attr])) {
                $props[] = "{$attr}: ".json_encode($meta[$attr]).' as const';
            }
        }

        $keyJs = json_encode($key);
        return "{$keyJs}: { ".implode(', ', $props).' }';
    }
}
